### ISSUE TITLE
sickbeard_mp4_automator Support

### ISSUE THREAD

**Issue by andrewkhunn** [Nottt/deluge#1]
Is there any way I could convince you to add support for [sickbeard_mp4_automator](https://github.com/mdhiggins/sickbeard_mp4_automator)? This would allow me to transcode downloaded files before they hit a media manager (like Sonarr or Radarr) so they will be available for direct play though Plex without transcoding-on-the-fly. [I've tried to add it myself here](https://hub.docker.com/r/andrewkhunn/easy-deluge/), [but the builds are failing](https://hub.docker.com/r/andrewkhunn/easy-deluge/builds/bjxtwd5zgyyehsrpshba5rl/) and I am not quite sure why.

[This person](https://hub.docker.com/u/aront/) has added support for it to his Radarr and Sonarr builds in a clever way that shares config files between them and might be a good starting point for integration into easy_deluge.

Thanks for a great Deluge implementation regardless!

**Comment by Nottt** [comment]
Hi. I didn't think anyone else was using this yet lol ! Good to hear it's working good for you too. 

I've looked up your docker and I see a lot of mistakes in the syntax and structure, I suggest you keep docker documentation at hand when trying to do this kind of stuff. Also, rebuild the docker after every change you add to see what could be happening.

I've opened a dev branch, and I've submitted everything I think I'll need to be able to use, but I haven't tested it ( time is short here so if you can help testing it would be great ),

All you have to do now is put the python script file where you mapped your /config in your host.

For example put `delugePostProcess.py ` and `autoProcess.ini` in /opt/deluged/mp4 and then in your deluge web-interface, put the script path as /config/deluged/mp4/ 

But I also wonder, why not just use the radarr/sonarr scripts? 
  
I also would appreciate if you could write the documentation about this feature, like how to use it, how to set it up, since I could use it too :P 

Also if you want to add more stuff like this ( I make the code, you document and test it ) let me know :D

**Comment by andrewkhunn** [comment]
I'll ultimately be using this with Cloudbox, just like your implementation (which is how I found this, via following your fork). So plugging this back in to Cloudbox is the end goal. You're right my syntax is likely horrible as I was essentially just combining two implementations. Complete newb to docker and need to do some more reading for sure.

I am trying to add support for this to Deluge and NZBGet (eventually) because I found that transcoding the files before handing them off to Sonarr/Radarr avoids some issues they have with their own file renaming operations. Namely, that they transcode the files correctly, but don't actually update the transcoded filename in the webui.

In my earlier testing (pre-Cloudbox), I actually needed to have both downloaders (NZBGet/Deluge) AND media managers (Sonarr/Radarr) using the sickbeard scripts to get everything working as intended. Using `postSonarr.py` and `postRadarr.py` adds appropriate metadata to the transcoded files. I wouldn't be opposed to running sickbeard_mp4_automator only at the Sonarr/Radarr level providing everything would work that way too.

I think there might be a few dependencies we're still missing in the Dockerfile, but I'll test later and submit a pull request if I find anything.

Thanks so much for working on this!

**Comment by Nottt** [comment]
Np... have you done any testing yet? I've pushed some fixes and new features to the master branch already...

**Comment by Nottt** [comment]
Let me know if you find anything new on this.

**Comment by Nottt** [comment]
Closing this as there isn't any new activity.
